# ANSIBLE_ROLE="demo"
# ANSIBLE_HOME="/home/vagrant/.ansible/"
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"
  #config.vm.synced_folder "../", "#{ANSIBLE_HOME}/roles/", type: 'rsync'
  # The working ansible directory created by ansible_local is owned by root
  # config.vm.provision "shell", inline: "chown vagrant:vagrant #{ANSIBLE_HOME}"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yaml"
  end
  
end
